create database Retail_CaseStudy

use Retail_CaseStudy

select * from Transactions
select * from Customer
select * from prod_cat_info

alter table Transactions add constraint fk_Customer_Id_Id foreign key (cust_Id)
references Customer (customer_Id) on update cascade;

--- Q1 Total number of the rows in each of the 3 tables in database.

select count(*) as Cust_Total from Customer

select count(*) as Transactions_Total from Transactions

select count(*) as prod_Cat_Total from  prod_cat_info

---Q2 What is the total number of transactions that have a return.

select count(*) as Total_Num_Trans from Transactions where total_amt > 0 

---Q3 Convert the date varibles into valid date formats before proceeding ahead.

select convert(varchar(10),cast(tran_date as datetime),105) as [DD-MM-YY] from Transactions
select convert(varchar(10),cast(DOB as datetime),105) as [DD-MM-YY] from Customer

--- Q4 What is the time range of transaction data avilable for analysis? Show the output in number of days, month and year simultaneously in different columns.

Select Datediff(day,Min((CONVERT(date, tran_date, 103))),Max(CONVERT(date, tran_date, 103))) as days,
Datediff(month,Min((CONVERT(date, tran_date, 103))),Max(CONVERT(date, tran_date, 103))) as months,
Datediff(year,Min((CONVERT(date, tran_date, 103))),Max(CONVERT(date, tran_date, 103))) as years
 from [dbo].[Transactions]
     
--- Q5 Which product category does the sub-category "DIY" belong to ?

select prod_cat, prod_subcat from prod_cat_info where prod_subcat ='DIY'

---DATA ANALYSIS
--- Q1 Which channel is most frequently used for transactions ?

select count (Store_type) as Count_Tr,
       count (tran_date) as Tran_Date,
	   count (c.customer_Id) as Count_CS,
	   Store_type, tran_date, c.customer_Id from Transactions as T join Customer as c on T.cust_id= c.customer_Id
	   group by Store_type, tran_date, c.customer_Id

--- Q2 What is the count of male and female customers in the database.

select 
count(case when Gender='M' then cust_id end) as Males,
count(case when Gender='F' then cust_id end) as Females,
count(*) as Total
from Customer, Transactions

--- Q3 From which city do we have the maximum number of customers and how many ?

select top 1 city_code , count(cust_id) as Total_Customer from Customer inner join
Transactions on Customer.customer_Id= Transactions.cust_id
group by city_code
order by count(1) desc

--- Q4 How many sub categories are there under the books category ?

select count(prod_sub_cat_code) as Total_Num_Sub_cat, prod_cat from prod_cat_info inner join
Transactions on prod_cat_info.prod_sub_cat_code= Transactions.prod_subcat_code
where prod_cat= 'Books'
group by prod_cat
order by count(1) desc

--- Q5 What is the maximum quantity of products ever ordered ?

select top 1 prod_cat, count(prod_cat) as Max_Qnt from Transactions, prod_cat_info
where prod_cat_info.prod_cat_code= Transactions.prod_cat_code
group by prod_cat
order by count(1) desc

--- Q6 What is the net total revenue generated in categories Electronics and Books ?

select prod_cat, sum(total_amt) as Total_Revenue
from prod_cat_info, Transactions
where prod_cat_info.prod_cat_code= Transactions.prod_cat_code and prod_cat= 'Books'
group by prod_cat 
union all
select prod_cat, sum(total_amt)
from prod_cat_info, Transactions
where prod_cat_info.prod_cat_code= Transactions.prod_cat_code and prod_cat= 'Electronics'
group by prod_cat

--- Q7 How many customers have > 10 transactions with us excluding returns ?

SELECT count(*) as Total_Customer_More_10_Transaction FROM
( select count(*) as Customer_More_10_Transaction
from    dbo.Transactions
group by cust_id
having count (*) > 10
) as T

--- Q8 What is the combined revenue earned from the "Electronics" & "Clothing" categories from "Flagship Stores" ?

select sum(total_amt) as Amount from Transactions inner join
prod_cat_info on prod_cat_info.prod_cat_code= Transactions.prod_cat_code
and prod_cat_info.prod_sub_cat_code= Transactions.prod_subcat_code
where prod_cat in ('Clothing','Electronics') and Store_type ='Flagship store'

--- Q9 What is the total revenue generated from male customers in "Electronics" ? output should display total revenue by Product sub-cat.

select prod_subcat, sum(total_amt) as Revenue
from Transactions left join
Customer on cust_id= customer_Id left join
prod_cat_info on prod_cat_info.prod_sub_cat_code= Transactions.prod_subcat_code and
prod_cat_info.prod_cat_code= Transactions.prod_cat_code
where Transactions.prod_cat_code= '3' and Gender= 'M'
group by Transactions.prod_cat_code, prod_subcat

--- Q10 What is the percentage of sales and returns by sub category; display only top 5 sub categories in terms of sales ?


--- Q11 For all customers aged between 25 to 35 years find what is net total revenue generated by these consumers in last 30 days of transactions of max transactions date avilable in the data ?

Select cust_id,sum(total_amt) as Revenue from Transactions
where cust_id in (
select customer_Id from Customer
where datediff(year, convert(date,DOB,103),getdate()) between 25 and 35)
and convert(date,tran_date,103) between dateadd(day,-30,(select max(convert(date,tran_date,103)) from Transactions)) 
and( select max(convert(date,tran_date,103)) from Transactions)
group by cust_id